### ISSUE TITLE
Doesn't work with Antergos/Arch Gnome 3.32

### ISSUE THREAD

**Issue by Taylor-Schmidt-NDSU** [arelange/gnome-shell-extension-hibernate-status#29]
Was working very well until I updated to Gnome 3.32. The button is still there, and alt-click will perform the hybrid sleep. However, when clicking the hibernate button regularly, nothing happens. The dialog box does not even pop up

This is the same issue that #26 was supposed to fix, however after updating I have not noticed any change. 

Side-note "sudo systemctl hibernate" does work on my machine

**Comment by hebrewd** [comment]
I have the same issue on fedora 30.
I am able to hibernate with systemctl hibernate(No need for sudo due to polkit preconfigured on fedora)
Looking at journalctl I get the following error:  
```
gnome-shell[1669]: JS ERROR: TypeError: this._construct is not a function
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
 _onHibernateClicked@/home/binyamin/.local/share/gnome-shell/extensions/hibernate-status@dromi/extension.js:127:24
 wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22

**Comment by p91paul** [comment]
From your log, it appears you are running an old version of this extension. Line 127 of file extension.js, that appears in your error, is an empty line in current master and in latest v15 from extensions.gnome.org. Looking at a previous version there was code there, and that code matches with your error.
Please try to remove and reinstall the extension.

**Comment by hebrewd** [comment]
@p91paul yes, that was indeed it.
I had to completely purge the extension that I had installed, restart the gnome session and install the new one, that did seem to do the trick, thanks!

**Comment by p91paul** [comment]
good! closing this one then
